Feat/release staging
Academia-750/academy750-backend-laravel pull request #2
Opened 2023-07-11 11:19 UTC by abelbordonado

## Context

Made some changes on the migrations (were broken and I couldn't generate them) 
On the README and package.json.

The goal was to be able to generate a new instance in the staging server

> [Staging Server](https://academy750.tianlu.tech/)

2023-07-13 12:54 UTC, kayiganwa04 requested changes

2023-07-13 12:54 UTC, kayiganwa04 commented on README.md
> +USE mindkind
USE mindkind 🐞

2023-07-14 09:38 UTC, abelbordonado commented on README.md
> +GRANT ALL ON `bomberos_test`.* TO `mindkind`@`localhost`;
Damm good comment

2023-07-14 12:23 UTC, kayiganwa04 approved these changes
One question how about the issues of not getting the password in the email? you remember for us we had to edit student password in the database manually

2023-07-14 12:29 UTC, abelbordonado commented
> One question how about the issues of not getting the password in the email? you remember for us we had to edit student password in the database manually

I had dig into it, I think I need to configure the EMAIL server in staging to get the emails. 
They were using mailtraip.io for testing.

I will get it done but we can approve this PR (is config not code)

2023-07-14 15:33 UTC, abelbordonado commented
Approved as part of #4

2023-07-17 08:58 UTC, kayiganwa04 approved these changes
Approved

2023-07-17 09:07 UTC, kayiganwa04 approved these changes
Appoved

2023-07-17 09:59 UTC, merged